<a href="https://colab.research.google.com/github/Harvy7777/Harvy/blob/main/dsw_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name : Atharva Waghare

UId : 25006037

Batch : d2



In [ ]:
# Import required libraries
import numpy as np
import pandas as pd

# -----------------------------
# a) 1D NumPy Array Operations
# -----------------------------
arr = np.array([10, 20, 30, 40, 50])

print("1D Array:", arr)
print("Shape of array:", arr.shape)
print("Sum of elements:", arr.sum())
print("Mean of elements:", arr.mean())


# -----------------------------
# b) 3x3 NumPy Matrix Operations
# -----------------------------
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("\nOriginal Matrix:\n", matrix)
print("Transpose of Matrix:\n", matrix.T)
print("Matrix multiplied by 3:\n", matrix * 3)


# -----------------------------
# c) Pandas DataFrame Operations
# -----------------------------
data = {
    "Name": ["Atharva", "Rahul", "Sneha", "Priya"],
    "Marks": [75, 55, 82, 60],
    "City": ["Mumbai", "Pune", "Delhi", "Chennai"]
}

df = pd.DataFrame(data)

print("\nFull DataFrame:\n", df)

print("\nOnly Name Column:\n", df["Name"])

print("\nStudents scoring more than 60 marks:\n", df[df["Marks"] > 60])

1D Array: [10 20 30 40 50]
Shape of array: (5,)
Sum of elements: 150
Mean of elements: 30.0

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of Matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Matrix multiplied by 3:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]

Full DataFrame:
       Name  Marks     City
0  Atharva     75   Mumbai
1    Rahul     55     Pune
2    Sneha     82    Delhi
3    Priya     60  Chennai

Only Name Column:
 0    Atharva
1      Rahul
2      Sneha
3      Priya
Name: Name, dtype: object

Students scoring more than 60 marks:
       Name  Marks    City
0  Atharva     75  Mumbai
2    Sneha     82   Delhi


In [ ]:
# -----------------------------
# a) List Operations
# -----------------------------

# Create a list of 5 numbers
numbers = [10, 20, 30, 40, 50]
print("Original List:", numbers)

# Append a new number
numbers.append(60)

# Insert a number at index 2
numbers.insert(2, 25)

# Remove the last element
numbers.pop()

# Print the final list
print("Final List:", numbers)


# -----------------------------
# b) Dictionary Operations
# -----------------------------

# Create a dictionary with student data
student = {
    "Name": "Atharva",
    "Age": 18,
    "Branch": "Computer Science"
}

print("\nOriginal Dictionary:", student)

# Add a new key 'Marks'
student["Marks"] = 85

# Update the value of Age
student["Age"] = 19

# Print all keys and values
print("Updated Dictionary:")
for key, value in student.items():
    print(key, ":", value)


# -----------------------------
# c) Set Operations
# -----------------------------

# Create a set of numbers
num_set = {1, 2, 3, 4, 5}
print("\nOriginal Set:", num_set)

# Add a new element
num_set.add(6)

# Remove an element
num_set.remove(3)

# Print the final set
print("Final Set:", num_set)

Original List: [10, 20, 30, 40, 50]
Final List: [10, 20, 25, 30, 40, 50]

Original Dictionary: {'Name': 'Atharva', 'Age': 18, 'Branch': 'Computer Science'}
Updated Dictionary:
Name : Atharva
Age : 19
Branch : Computer Science
Marks : 85

Original Set: {1, 2, 3, 4, 5}
Final Set: {1, 2, 4, 5, 6}


In [ ]:
import seaborn as sns
import pandas as pd

# -----------------------------
# a) Load Titanic Dataset
# -----------------------------
titanic = sns.load_dataset("titanic")

print("\nFirst 5 rows of Titanic dataset:\n", titanic.head())


# -----------------------------
# b) Extract age column (remove missing values)
# -----------------------------
age_array = titanic["age"].dropna().to_numpy()

print("\nFirst 10 Age values:", age_array[:10])
print("Shape of age array:", age_array.shape)


# -----------------------------
# c) Multi-dimensional NumPy array
#    Columns: age, fare, sibsp, parch
#    After dropping missing values
# -----------------------------
selected_data = titanic[["age", "fare", "sibsp", "parch"]].dropna()

multi_array = selected_data.to_numpy()

print("\nShape of multi-dimensional array:", multi_array.shape)


# -----------------------------
# d) Create new DataFrame from multi-dimensional array
# -----------------------------
new_df = pd.DataFrame(multi_array, columns=["age", "fare", "sibsp", "parch"])

print("\nFirst 5 rows of new DataFrame:\n", new_df.head())


First 5 rows of Titanic dataset:
    survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  

First 10 Age values: [22. 38. 26. 35. 35. 54.  2. 27. 14.  4.]
Shape of age array: (714,)

Shape of multi-dimensional array: (714, 4)

First 5 rows of new DataFrame:
     age     fare